[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
fileWatcherType = "poll"

[client]
showErrorDetails = true

[runner]
magicEnabled = true

[app]
# 👇 This is the KEY LINE
pages_dir = "src/pages"
